name: publish
on: [push]
jobs:
  publish-base-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the base image
      run: |
            cd ./images/base
            docker build . --tag ghcr.io/chrisbalmer/coder-images-base:latest
            docker run ghcr.io/chrisbalmer/coder-images-base:latest
            docker push ghcr.io/chrisbalmer/coder-images-base:latest
    - name: Build the golang image
      run: |
            cd ./images/golang
            docker build . --tag ghcr.io/chrisbalmer/coder-images-golang:latest
            docker run ghcr.io/chrisbalmer/coder-images-golang:latest
            docker push ghcr.io/chrisbalmer/coder-images-golang:latest